### ISSUE TITLE
Add ChannelProperties as part of 1.0 spec (RTL15)

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-ruby#112]
[RTL15](https://docs.ably.io/client-lib-development-guide/features/#RTL15)

See full spec at https://github.com/ably/docs/pull/260

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-457) by [Unito](https://www.unito.io/learn-more)

**Comment by TheSmartnik** [comment]
https://github.com/ably/ably-ruby/pull/227
