### ISSUE TITLE
WebSocket driver does not emit events for heartbeats

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-ruby#116]
The library we use https://github.com/faye/websocket-driver-ruby does not support emitting events for heartbeats.

We will disabled native heartbeats until that is forked and support is added.

**Comment by mattheworiordan** [comment]
Waiting for https://github.com/faye/websocket-driver-ruby/pull/51 to be merged upstream before releasing a permanent fix

**Comment by funkyboy** [comment]
Update: https://github.com/faye/websocket-driver-ruby/pull/51 has been merged.

**Comment by mattheworiordan** [comment]
Nice.  Should be easy enough now to change Ruby to use native heartbeats 👍
