### ISSUE TITLE
Check fallback functionality is being used after timeouts

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-ruby#126]
Customer reporting getting occasional `Faraday::ConnectionFailed` and `Net::ReadTimeout` errors with REST publishes. On timeout errors the lib should be retrying the request (to a different datacenter) per RSC15d, and it should have time to make at least a second attempt no matter what class of timeout is encountered on the first attempt per TO3l4 and TO3l6. Need to verify that this happens for both those classes of timeout errors, and fix it if not.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4078) by [Unito](https://www.unito.io)

**Comment by mattheworiordan** [comment]
> Need to verify that this happens for both those classes of timeout errors, and fix it if not.

I am not sure there is any evidence this is not happening, and as far as I can tell, so long as the ClientOptions are configured correctly, this is guaranteed.  There are tests for this too https://github.com/ably/ably-ruby/blob/master/spec/acceptance/rest/client_spec.rb#L571-L614

**Comment by SimonWoolf** [comment]
>  There are tests for this too 

There are, but at a closer look I'm not quite convinced by them. e.g. they pass a `max_retry_duration` param, but that's just ignored as the lib expects it to be `http_max_retry_duration`. Which is why the second test is passing even though it expects the opposite of what should happen (ie it [asserts that a fallback](https://github.com/ably/ably-ruby/blob/master/spec/acceptance/rest/client_spec.rb#L611) was tried even though it's passing options that should mean no fallbacks are tried). Even after that's fixed, fallbacks seem to be completely broken for GET, probably due to https://bugs.ruby-lang.org/issues/10674

That said, except for the GET issue those are all test bugs, and at least for POST the lib seems to be working as expected afaict -- and the requests the customer was complaining about are POSTs rather than GETs. So happy for you to close this.

Pushed some fixed (and so failing for GETs) tests up to https://github.com/ably/ably-ruby/compare/fallback-on-timeout-spec?expand=1
