### ISSUE TITLE
Add JWT test

### ISSUE THREAD

**Issue by funkyboy** [ably/ably-ruby#136]

**Comment by mattheworiordan** [comment]
Is there not a spec for what needs to be tested for JWT?

**Comment by mattheworiordan** [comment]
See https://github.com/ably/ably-ruby/pull/137#pullrequestreview-113537268 for reference.

@paddybyers do we not have a spec item for this in our client lib spec?  We need to be explicit about what scenarios we need testing.

**Comment by paddybyers** [comment]
> do we not have a spec item for this in our client lib spec? We need to be explicit about what scenarios we need testing.

There's an issue to add that: https://github.com/ably/docs/issues/416
