### ISSUE TITLE
client_id should be passed as clientId

### ISSUE THREAD

**Issue by funkyboy** [ably/ably-ruby#159]
``` ruby
rest_client = Ably::Rest.new(..., auth_url: 'YOUR_SERVER')
rest_client.auth.request_token({client_id: '123'})
```

check your server logs and you'll see `?client_id=123`.
It should be `?clientId=123` per spec https://docs.ably.io/client-lib-development-guide/features/#TK2c

**Comment by mattheworiordan** [comment]
Thanks, will take a look.  Should be a simple matter of ensuring the Idiomatic module is used before sending the HTTP request.

**Comment by TheSmartnik** [comment]
Cannot reproduce. Currently `cliend_id` passed correctly as `clientId` and we have specs covering that https://github.com/ably/ably-ruby/blob/main/spec/acceptance/rest/auth_spec.rb#L92-L119
