### ISSUE TITLE
stubbing for testing

### ISSUE THREAD

**Issue by modosc** [ably/ably-ruby#175]
what's the preferred way to stub stuff out in tests? we don't want our clients making actual calls in specs. 

for comparison, segment-io has a `stub` option which disables all actual network calls (and won't throw any errors with invalid api keys):

https://github.com/segmentio/analytics-ruby#testing

**Comment by mattheworiordan** [comment]
@modosc apologies, we missed this question 👎 

What testing suite do you use?

**Comment by modosc** [comment]
rspec - currently we're doing this hacky solution:
```
  if Rails.env.test?
    # mock our ably rest client here because the actual client doesn't provide a stub mode
    # and there's no simple / global way to do this in rspec (at least that i could find?)

    class AblyRestStub

      class StubHash < Hash

        include Hashie::Extensions::MethodAccess

      end

      def options
        { key: "asdf.asdf:asdf_asdf" }
      end

      def channel
        channel = StubHash.new
        channel.presence = StubHash.new
        channel.presence.get = StubHash.new
        channel.presence.get.items = []
        channel
      end

      def auth
        # noop
      end

    end
  end
```
but something official / clean would be nice. aws also does a nice job of this for testing:
https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/stubbing.html

**Comment by piotrpawlik** [comment]
@modosc Have you found a good way to stub ably?
