### ISSUE TITLE
RTN16b recovery not fully implemented

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-ruby#180]
See https://github.com/ably/docs/commit/1b3667632a39b7de18d4ef5883f128f63297dc3d

And implementation of recovery key https://github.com/ably/ably-ruby/blob/master/lib/ably/realtime/connection.rb#L303-L307

It contains no `msgSerial`.

@SimonWoolf @paddybyers before I go and implement this, I do think the spec should be a bit clearer about how this string is constructed i.e. https://docs.ably.io/client-lib-development-guide/features/#RTN16b just states the key is composed of attributes, where as https://docs.ably.io/client-lib-development-guide/features/#RTP2b2 for example is far more explicit with `which will be of the form connid:msgSerial:index, e.g. aaaaaa:0:0`.  I assume you agree an update to the spec to be more explicit abut this makes senes?

**Comment by paddybyers** [comment]
> I assume you agree an update to the spec to be more explicit abut this makes senes?

Yes
