### ISSUE TITLE
EventMachine Reactor Realtime Loop

### ISSUE THREAD

**Issue by Welfordian** [ably/ably-ruby#190]
Within an action in my app I want to be able to publish an event to a channel, but it seems that `EventMachine.stop` is never called after publishing to a channel and thus the application crashes as it falls into an infinite loop. How does one accomplish this? I just want to publish to a channel and return a redirect... I don't want to keep the connection alive. Calling `EventMachine.stop` manually causes a premature end to the connection and the message is never published.

**Comment by SimonWoolf** [comment]
To be clear, you're trying to close the connection immediately after the message is published? If so, I'd strongly recommended that you instead [use the REST version of the library](https://github.com/ably/ably-ruby#using-the-rest-api), where publish calls are synchronous and not run from with EventMachine. The Realtime/EventMachine version of the library is designed for people who want to keep a connection to Ably more or less permanently open, e.g. so they can receive messages (not just publish them). See https://github.com/ably/ably-ruby#using-with-rails-or-sinatra for more information.
