### ISSUE TITLE
Feature request: support for batch requests

### ISSUE THREAD

**Issue by rgraff** [ably/ably-ruby#201]
Bulk publish and bulk presence would be nice: https://www.ably.io/documentation/rest-api/beta#batch

Any idea when these will be out of beta?

Thanks.

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-540) by [Unito](https://www.unito.io)

**Comment by JackUkleja** [comment]
@rgraff I've checked with the team and we no longer consider this feature to be "beta". 

The API is stable, and it is being used in production by several of our customers.

The main reason it was still languishing in beta was because there were ambitions at one point to provide an API beyond just `request()` but we no longer have a timescale for that.

I've put a task to update the docs into our backlog.

**Comment by rgraff** [comment]
Are you going to add support (convenience methods, really) to the clients? specifically, `ably-ruby`. The code examples are all JS in the docs.

**Comment by mattheworiordan** [comment]
Hey @rgraff 

We have no plans at present to add convenience methods just yet as we introduced the request method specifically to give us flexibility to add new API methods without having to roll out new SDKs each time.

Here is a Ruby equivalent if that helps:

```ruby
ably = Ably::Rest.new(key: 'dFMjJg.lt-i5g:1a_LuqzpDfkpiAM2', environment: 'dev')
content = { "channels": [ "test1", "test2" ], "messages": { "data": "myData" } }
response = ably.request('post', '/messages', nil, content, nil)
response.success? #=> true
response #=> <Ably::Models::HttpPaginatedResponse:70093508156320
  # @base_url="/",
  # @last?=true,
  # @has_next?=false,
  # @items=
  #    {"channel"=>"test1", "messageId"=>"M2H1MbMxfB:0"},
  #    {"channel"=>"test2", "messageId"=>"1idybVV_5e:0"}
  #>

content = { "channels": [ "test1", "test2" ], "messages": { "data": "myData", "extras": { "push": "not-allowed" } } }
response = ably.request('post', '/messages', nil, content, nil)
response.success? #=> false
response.error_code #=> 40020
response.error_message #=> "Batched response includes errors (status: 400, code: 40020) (code: 40020, http status: 400) -> see https://help.ably.io/error/40020 for help"
```

Out of interest, can you tell me a bit about what you're using batch publishing for?  We may very well consider adding this to the spec down the line, so knowing why people need this helps.

**Comment by mattheworiordan** [comment]
Hey @rgraff 

We have no plans at present to add convenience methods just yet as we introduced the request method specifically to give us flexibility to add new API methods without having to roll out new SDKs each time.

Here is a Ruby equivalent if that helps:

```ruby
ably = Ably::Rest.new(key: 'OBFUSCATED_KEY')
content = { "channels": [ "test1", "test2" ], "messages": { "data": "myData" } }
response = ably.request('post', '/messages', nil, content, nil)
response.success? #=> true
response #=> <Ably::Models::HttpPaginatedResponse:70093508156320
  # @base_url="/",
  # @last?=true,
  # @has_next?=false,
  # @items=
  #    {"channel"=>"test1", "messageId"=>"M2H1MbMxfB:0"},
  #    {"channel"=>"test2", "messageId"=>"1idybVV_5e:0"}
  #>

content = { "channels": [ "test1", "test2" ], "messages": { "data": "myData", "extras": { "push": "not-allowed" } } }
response = ably.request('post', '/messages', nil, content, nil)
response.success? #=> false
response.error_code #=> 40020
response.error_message #=> "Batched response includes errors (status: 400, code: 40020) (code: 40020, http status: 400) -> see https://help.ably.io/error/40020 for help"
```

Out of interest, can you tell me a bit about what you're using batch publishing for?  We may very well consider adding this to the spec down the line, so knowing why people need this helps.
