### ISSUE TITLE
JTW test failing  when using JWT with auth_url and credentials are wrong disconnected includes and invalid signature message

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-ruby#204]
See https://travis-ci.org/github/ably/ably-ruby/jobs/724120006#L6345-L6544

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-481) by [Unito](https://www.unito.io)

**Comment by TheSmartnik** [comment]
The issue is no longer reproducible while we still have a few flaky specs none of them are jwt related
