### ISSUE TITLE
Builds failing on some platforms

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-ruby#206]
Recent PR https://github.com/ably/ably-ruby/pull/205 has some failing tests, but only on some platforms.  See https://travis-ci.org/github/ably/ably-ruby/builds/731748516.

Sample of errors:

```
rspec ./spec/unit/logger_spec.rb:138 # Ably::Logger with a custom Logger with a valid interface delegates log messages to logger
rspec ./spec/unit/logger_spec.rb:20 # Ably::Logger internals delegates to the default Logger object
```

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-482) by [Unito](https://www.unito.io)

**Comment by TheSmartnik** [comment]
Fixed with https://github.com/ably/ably-ruby/pull/352
