### ISSUE TITLE
Lib apparently closing the socket after each request

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-ruby#211]
Customer reports that the current excon/Faraday setup is not using tcp keepalive, and is closing the tcp socket after each rest request. I haven't investigated, but if this is indeed the case then that's an unnecessary amount of extra work for every connection after the first, and we should fix that.

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-503) by [Unito](https://www.unito.io)

**Comment by TheSmartnik** [comment]
Should be fixed automatically when we switch to typhoeus(https://github.com/ably/ably-ruby/pull/197). Since curl reuses connections by default https://curl.se/mail/lib-2005-11/0073.html

**Comment by lukaszsliwa** [comment]
I have analyzed requests and headers. Ably REST client makes requests using HTTP/1.1 and no header is needed to use keep-active connection. This is a default behavior for HTTP/1.1 and the lib supports this correctly.

https://en.wikipedia.org/wiki/HTTP_persistent_connection

    In HTTP 1.1, all connections are considered persistent unless declared otherwise.

HTTP 1.0 it requires to use `Connection: Keep-Active`. Current Faraday setup has been implemented `typhoeus` adapter with HTTP/2 support.

https://github.com/ably/ably-ruby/blob/main/lib/ably/rest/client.rb#L688
