### ISSUE TITLE
Create code snippets for homepage (ruby)

### ISSUE THREAD

**Issue by jamienewcomb** [ably/ably-ruby#249]
**What**

We need to create Ruby code snippets for the ably homepage as outlined in [https://ably.atlassian.net/browse/SDK-878](https://ably.atlassian.net/browse/SDK-878|smart-link) .

The Ruby snippets needed are:

* Chat (publish)
* GPS (publish)
* IoT (publish and subscribe)
* Live Updates (publish)
* Multi-user Spaces (publish)

Please refer to the existing JavaScript snippets:

[https://github.com/ably/homepage-snippets/tree/main/javascript](https://github.com/ably/homepage-snippets/tree/main/javascript|smart-link) 

**Acceptance criteria**

A PR should be raised in the homepage-snippets repository: [https://github.com/ably/homepage-snippets/pulls](https://github.com/ably/homepage-snippets/pulls)

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-881) by [Unito](https://www.unito.io)

**Comment by lukaszsliwa** [comment]
https://gist.github.com/lukaszsliwa/c01c9a0645579dedfb8329ff4d561947

**Comment by jamienewcomb** [comment]
Thanks @lukaszsliwa - we have just created a repo for these to go in. could you raise as a PR here please https://github.com/ably/homepage-snippets/pulls

**Comment by lukaszsliwa** [comment]
@jamienewcomb I have got `permission denied` when trying to push 

```
lukasz@tamer homepage-snippets % git push origin feature/rb-snippets
ERROR: Permission to ably/homepage-snippets.git denied to lukaszsliwa.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
lukasz@tamer homepage-snippets % 
```

**Comment by jamienewcomb** [comment]
@owenpearson think we need to grant more permissions

**Comment by owenpearson** [comment]
@lukaszsliwa I've given you write access now, please try again
