### ISSUE TITLE
Make CI Green

### ISSUE THREAD

**Issue by owenpearson** [ably/ably-ruby#254]
There appears to be a few tests failing at the moment. Also we're getting errors uploading code coverage to coveralls.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-959) by [Unito](https://www.unito.io)

**Comment by lukaszsliwa** [comment]
Solved coveralls issues here: https://github.com/ably/ably-ruby/pull/261
