### ISSUE TITLE
Write spec tests for RSC7a, RSC7c (RestClient)


### ISSUE THREAD

**Issue by AndyNicks** [ably/ably-ruby#279]
Write spec tests for : RSC7a, RSC7c
ensure they pass and that the affected API conforms to the 1.2 API design.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1071) by [Unito](https://www.unito.io)

**Comment by jamienewcomb** [comment]
Closing this as we have decided we will not do this
