### ISSUE TITLE
Write spec tests for RTL19, RTL19a, b, c

### ISSUE THREAD

**Issue by AndyNicks** [ably/ably-ruby#306]
Write spec tests for  RTL19, RTL19a, b, c  ensure they pass and that the affected API conforms to the 1.2 API design

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1107) by [Unito](https://www.unito.io)

**Comment by jamienewcomb** [comment]
Closing this as we have decided we will not do this
