### ISSUE TITLE
Missing token/auth options when calling for authorize()

### ISSUE THREAD

**Issue by lukaszsliwa** [ably/ably-ruby#343]
When calling for `auth.authorize()`, the `token_params` and `auth_options` are ignored (by default `nil`).
however client (Rest or Realtime) can customize and set auth/token options.

https://github.com/ably/ably-ruby/blob/main/lib/ably/realtime/client/incoming_message_dispatcher.rb#L144

```ruby
          when ACTION.Auth
            client.auth.authorize

```

https://github.com/ably/ably-ruby/blob/main/lib/ably/realtime/connection/connection_manager.rb#L540

```ruby
client.auth.authorize.tap do |authorize_deferrable|
            authorize_deferrable.callback do |token_details|
              logger.info { 'ConnectionManager: Token renewed succesfully following expiration' }
            end
          end
```

https://github.com/ably/ably-ruby/blob/main/lib/ably/rest/client.rb#L642

```ruby
if auth.token_renewable?
          auth.authorize
          yield
        else
          raise e
        end

```

By default token_params/auth_options is `nil`. Client can customize these options, so some attributes can by filled when creating `Ably::Rest::Client` or `Ably::Realtime::Client` instance

```ruby
def authorize(token_params = nil, auth_options = nil)

```

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-1604) by [Unito](https://www.unito.io)

**Comment by TheSmartnik** [comment]
Not sure, what you mean here since `authorize` uses defaults from `Auth` object unless explicitly provided. Hence no need to explicitly set them when calling `auth.authorize`. Maybe I'm mistaken though. Unassigning myself as I don't think the issue exists

**Comment by owenpearson** [comment]
I Agree that there isn't a bug here for the reasons mentioned above, so I'm gonna close this
