### ISSUE TITLE
Documentation on rubydoc.info is broken for 1.2.2 release

### ISSUE THREAD

**Issue by owenpearson** [ably/ably-ruby#371]
On https://www.rubydoc.info/gems/ably, the lists of classes / methods are empty.

https://www.rubydoc.info/gems/ably/1.2.1 is working so something must have gone wrong in the 1.2.2 release ([diff|https://github.com/ably/ably-ruby/compare/v1.2.1...v1.2.2]).

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4060) by [Unito](https://www.unito.io)

**Comment by owenpearson** [comment]
Running `yard server` locally seems to work fine

**Comment by lawrence-forooghian** [comment]
This seems OK now. Maybe it was an issue on rubydoc.info’s end? I’ll close this issue.
