### ISSUE TITLE
'ably-em-http-request' depends on defunct 'cookiejar' gem

### ISSUE THREAD

**Issue by carlhauck** [ably/ably-ruby#439]
`ably-em-http-request` (a dependency of the `ably` gem) depends on the `cookiejar` gem (https://github.com/dwaite/cookiejar), which is no longer maintained and has been archived.

After bumping/updating our `uri` and `net-http` versions in a project with the latest `ably` version (`1.2.7`), we started receiving the following error from the `cookiejar` gem: `uninitialized constant CookieJar::CookieValidation::PATTERN::IPV4ADDR (NameError)`.

We'd prefer to not have to pin `uri` and `net-http` versions in this project simply in order to use `ably`.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-5121) by [Unito](https://www.unito.io)

**Comment by lawrence-forooghian** [comment]
Hi @carlhauck, I was hoping that I’d be able to reproduce this issue by running our integration tests. For example, [this test run](https://github.com/ably/ably-ruby/actions/runs/11913070908/job/33198005635?pr=440) is using `net-http` version `0.5.0` and `uri` version `1.0.2`, which are the latest versions. However, I am not seeing any test failures that look similar to the error you shared.

There are a couple of things that might help me:

1. Could you please tell me which version of the `cookiejar` gem you were using? Although `cookiejar` is indeed archived, its author released version 0.3.4 in January 2024, in response to issues encountered by users of the gem from which our `ably-em-http-request` gem is forked (https://github.com/igrigorik/em-http-request/pull/358).
2. Would you be able to share some steps or example code to reproduce this issue?

**Comment by carlhauck** [comment]
We were using `cookiejar` `0.3.4` and `uri` `1.0.1`, but it actually looks like this was fixed 5 days ago in the `1.0.2` version release of `uri` (https://github.com/ruby/uri/releases): `Restore constants like URI::REGEXP::PATTERN::IPV6ADDR`.

So that explains why you weren't able to reproduce. Thanks for looking into it so quickly, @lawrence-forooghian!
