### ISSUE TITLE
Allow token ID or API key in the client constructor

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-ruby#5]
Either should be usable in the format `Ably::Realtime.new(api_key)` or `Ably::Realtime.new(token_id)`

**Comment by kouno** [comment]
Note: Documentation in README needs to be updated too to complete this task. In particular `Authentication with a token` needs to show a better example.

**Comment by mattheworiordan** [comment]
See https://github.com/ably/ably-js/compare/17855975bf9c...5a8ec244203b

**Comment by mattheworiordan** [comment]
Solved, https://github.com/ably/ably-ruby/pull/19
