### ISSUE TITLE
Connection retry and timeout needs to be configurable

### ISSUE THREAD

**Issue by kouno** [ably/ably-ruby#6]
The retry feature allows us to handle unreliable connections to Ably, but we have at the moment no proper way of configuring the number of retries or the period in between these retry.

https://github.com/ably/ably-ruby/blob/921838e4cc31cf7e92e02c2111e3f770a59407b9/lib/ably/realtime/connection/connection_manager.rb#L12-L21

It would be nice to add a DSL for this.

**Comment by paddybyers** [comment]
There are default retry timeouts.

When an event is delivered indicating a disconnection, it indicates how long it will be before the library will retry automatically. There is nothing to stop the application from retrying sooner if it wishes.

The connection at the Ably end will time out and be destroyed after a fixed period, so it is not completely up to the client to decide how many retries he wants.

**Comment by kouno** [comment]
> There are default retry timeouts.

It's fine if they are defaults. There still should be a nice way of overriding it (instead of changing a frozen hash :)).

> When an event is delivered indicating a disconnection, it indicates how long it will be before the library will retry automatically.

That may be the case for the javascript and java library but the ruby library does not do this.

`ably-ruby` has the wrong configuration right now. `suspended` state should only happen after 2 minutes and retry should happen every 15 seconds (that's what the documentation says) but the connection will try to reconnect every 500ms for 10 seconds (https://github.com/ably/ably-ruby/blob/921838e4cc31cf7e92e02c2111e3f770a59407b9/lib/ably/realtime/connection/connection_manager.rb#L13) and then go to suspended.

> The connection at the Ably end will time out and be destroyed after a fixed period, so it is not completely up to the client to decide how many retries he wants.

Fair enough. That should be a constant within the client libraries to not retry to reconnect after X amount of time, right?

**Comment by paddybyers** [comment]
> There still should be a nice way of overriding it

I would say that's possible, I think it's a stretch to say it's a should. At some point adding more and more optional "nice to have" functionality just makes things needlessly complex and obscure.

> When an event is delivered indicating a disconnection, it indicates how long it will be before the library will retry automatically.
> That may be the case for the javascript and java library but the ruby library does not do this.

I think it should.

> the connection will try to reconnect every 500ms for 10 seconds

I think that's far too frequent. I can't think of any real-life network condition that would mean that a connection attempt has a useful probability of succeeding only 500ms after it failed. You might still me resolving DNS on one attempt when you schedule the next one.

> That should be a constant within the client libraries to not retry to reconnect after X amount of time, right?

It is, it's the suspend timeout :)

**Comment by kouno** [comment]
> At some point adding more and more optional "nice to have" functionality just makes things needlessly complex and obscure.

Agreed that adding "nice to have" functionalities can make things more complex and obscure, but changing these constants to use variables instead sounds trivial. I'm advocating here that we are not changing an algorithm to make it more flexible, or changing a lot of our code structure to make this possible. Making these configurable should be pretty straightforward. 

It doesn't even have to be moved to the connection manager constructor. As long as you can change it with let's say `channel.connection.config = { retry: { disconnect: { retry_every: 0.5, max_time_in_state: 10 } } }` I would be okay with it.

Obviously, this also looks like it's low priority. So I wouldn't mind having this done later down the line when someone actually needs it :).

> I think that's far too frequent. I can't think of any real-life network condition that would mean that a connection attempt has a useful probability of succeeding only 500ms after it failed. You might still be resolving DNS on one attempt when you schedule the next one.

I'm creating another issue to fix this.

**Comment by kouno** [comment]
Created a PR concerning the timeout values https://github.com/ably/ably-ruby/pull/7.

**Comment by mattheworiordan** [comment]
See https://github.com/ably/realtime/issues/89#issuecomment-76233904, we need a proposal to describe behaviour if we want it to change

**Comment by mattheworiordan** [comment]
These are all configurable in https://github.com/ably/ably-ruby/pull/99
