### ISSUE TITLE
nodename nor servname provided

### ISSUE THREAD

**Issue by kethomassen** [ably/ably-ruby#65]
Getting an error while trying to publish messages via the rest client

```
.rvm/gems/ruby-2.2.3/gems/ably-rest-0.8.5/lib/submodules/ably-ruby/lib/ably/rest/client.rb:350:in `rescue in send_request': getaddrinfo: nodename nor servname provided, or not known (code: 80000) < getaddrinfo: nodename nor servname provided, or not known (Ably::Exceptions::ConnectionError)
```

this line seems to be the only line throwing this error:

``` ruby
Jackpot_Channel.publish("winner", { :type => "selecting", :bam => 1 })
```

using this config:

``` ruby
Ably_Client = Ably::Rest.new({ :key => 'xxx'})
Jackpot_Channel = Ably_Client.channel("jackpot")
Chat_Channel = Ably_Client.channel("chat")
```

**Comment by paddybyers** [comment]
@lmars : can you have a look?

**Comment by kethomassen** [comment]
Coming from here:
https://github.com/ably/ably-ruby/blob/master/lib/ably/rest/client.rb#L350

Looks like either a Faraday error or a server error on the ably backend.

**Comment by kethomassen** [comment]
http://stackoverflow.com/questions/4132525/getaddrinfo-nodename-nor-servname-provided-or-not-known

**Comment by mattheworiordan** [comment]
@kethomassen apologies for not getting back to you. I was on honeymoon, and I think @lmars must have forgotten :(

This is very odd, something I would only expect to see if you had a dodgy connection.  You can turn on a much higher level of debugging by doing `Ably::Rest.new(log_level: :debug)`. Would you mind trying again, and sending me the logs?

Sorry once again for the slow reply :(

**Comment by mattheworiordan** [comment]
Hi @kethomassen I am closing this issue as not heard back.  Please shout if you have this issue. BWT. Our 0.9 release is ready at https://github.com/ably/ably-ruby/pull/99
