### ISSUE TITLE
Ably::Exceptions::ConnectionError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-ruby#87]
If you're working on a Windows system and encounter something like:

`Ably::Exceptions::ConnectionError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (code: 80000) <SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed`

. . . the root certificates that your Ruby interpreter is using may be outdated. Here's a quick fix:

1. Download http://curl.haxx.se/ca/cacert.pem and save to a directory like C:\Users\me\root_ca

2. Create an environment variable called SSL_CERT_FILE with a value of C:\Users\me\root_ca\cacert.pem

3. Restart your terminal and/or server(s), and you should be good to go.

**Comment by btsai** [comment]
On Mac OSX, you can try this:
https://rvm.io/support/fixing-broken-ssl-certificates
