### ISSUE TITLE
Several problems with fallback hosts

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-ruby#95]
See [this gist](https://gist.github.com/SimonWoolf/3dcef6f40103c069021379bd0c3ad6e8). Several issues:

- ably-ruby seems to use a fallback host when reconnecting after an unexpected disconnection, rather than only after it gets an RSC15d error from the primary host. (Normally not a problem, but becomes one when inter-region forwarding isn't working)

- it's cycling through the fallback hosts again and again, without retrying the original host. (Again, normally not a problem, but becomes one when inter-region forwarding isn't working)

- it's incorrectly still trying to resume even after going into SUSPENDED (so it knows the connection's gone in realtime), which makes the problem worse (since a resume needs to be routed to the right region; a fresh connection wouldn't):
```
 0:54:23.954 DEBUG [xPPhdbHLtK] Ably::Realtime::Connection: StateEmitter changed from STATE.Suspended => connecting
20:54:23.954 DEBUG [xPPhdbHLtK] ConnectionManager: Opening a websocket transport connection
20:54:23.954 DEBUG [xPPhdbHLtK] ConnectionManager: Setting up automatic connection timeout timer for 10s
20:54:23.954 DEBUG [xPPhdbHLtK] Resuming connection key 108a2235!xPPhdbHLtKlTMDdJ-e7010108a2235 with serial 45
20:54:23.955 DEBUG [xPPhdbHLtK] Connection: Opening socket connection to realtime.ably.io:443 and URL 'wss://realtime.ably.io?key=<redacted>&format=msgpack&echo=true&resume=108a2235%21xPPhdbHLtKlTMDdJ-e7010108a2235&connection_serial=45'
```

**Comment by mattheworiordan** [comment]
OMG, you are insinuating there is a bug in the Ruby library! That's blasphemy 👍 

I'll look this weekend as I plan to release REST 0.9 as well this weekend and defer Realtime 0.9 until I have some time :/
