### ISSUE TITLE
Catch common SSL error and show docs

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-ruby#96]
See https://github.com/ably/ably-ruby/issues/87

This is common and leaves people struggling.  We should catch this error and point them to the issue and steps to correct, see https://support.ably.io/solution/articles/3000052806-ssl-certificate-issues-communicating-with-ably-

**Comment by btsai** [comment]
On Mac OSX, try this:
https://rvm.io/support/fixing-broken-ssl-certificates

**Comment by mattheworiordan** [comment]
Thanks @btsai
